using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RealtimeSpreadMonitor.GMI
{
    public enum RCG_TRND
    {
        FRECID = 0, FFIRM, FOFFIC, FRR, FACCT, FCLASS, FSUBCL, FATYPE, FCARD,
        FBS, FQTY, FSDSC1, FPRTPR, FTDATE, FOC, FCTYM, FSBCUS, FSTYPE, FSUBTY,
        FSTRIK, FEXPDT, FSPRED, FSNAME, FSRCAC, FSDATE, FEXCH, FTRDEX, FFC, FSYMBL,
        FPTYPE, FTPRIC, FCALC, FCMNT1, FCMNT2, FGIVIO, FGIVF,FBQTY,FSQTY,FCURAT,
        FMKVAL,FMULTF,FCLOSE,FCUSIP,FTRACE,FSUBAC,FBROKR,FREFNO,FMEMBR,FDELTA,FLTDAT,
        FTYPE,FMATDT,FUNDCP,FCURSY,FCURCD,FCMNT3,FOMNCD,FRTHT,FEXBKR,FORDER,FCHIT,FCTI,
        FMTABL,FREL1F,FREL1O,FREL1A,FREL1T,FDELET,FSDSC2,FCOMM,FFEE1,FFEE2,FFEE3,FFEE4,
        FFEE5,FFEE6,FFEE7,FFEE8,FFEE9,FGICHG,FBKCHG,FOTHER,FGROSS,FNET,FMBKOF,FMFLOR,FMORDR,FMWIRE,FMOTHR
    }

    public enum RCG_POS
    {
        RID = 0, FRM, OFF, REG_REP_SLSMN, ACCT, CLS, SUB_CLS, ATYP, CARD, B_S, QUANTITY, SDSC1,
        Printable_Price, TRD_DT, OPN_CLS, CTYM, SBCUS, STYP, SUBTY, STRIK, EXP_DT, SPR,
        ACCOUNT_SHORT_NAME, SRC_A_C, SETTL, EX, TRACNO, FC, SYMBOL, PTYP, TPRIC, CC, C1, C2,
        GIO_CD, GIO_F,BQTY,SQTY,ACT_TYP_CUR,MKT_VAL,MLT_FCT,CLOSE,CUSIP,TRACER,SBACT,BRKR,SRC_REF_NO,
        MBR,DELTA,LSTD,TYPE,MAT_DATE,UNDCLS,CSY,PROD_CURR_CODE,C3,OMNB_CODE,RT_HT,EXBKR,ORDER_NO,
        CHIT_NUMBER,CTI,M_TABLE,REL_FRM_1,REL_OFF_1,REL_ACCT_1,REL_TYP_1,COMM,FEE1,FEE2,FEE3,FEE4,FEE5,
        FEE6,FEE7,FEE8,FEE9,G_I_O_CHG,BKCHG,OTHER,GROSS,NET_AMT,BK_OFF,FLR_CHG,ORD,WIRE,OTHR,AT_COMM,
        AT_FEE1,AT_FEE2,AT_FEE3,AT_FEE4,AT_FEE5,AT_FEE6,AT_FEE7,AT_FEE8,AT_FEE9,AT_GIV,AT_BKG,AT_OTHER,
        AT_BKO,AT_FLOOR,AT_ORDER,AT_WIRE,ALOC_CHRG_AT
    }
}
